title: studio cecillie
baseline: Le studio de conseil technique et créatif
description: Le studio cecillie est le studio de conseil technique et créatif de Cécile Ricordeau et Arnaud Ligny.
baseurl: https://studio.cecillie.fr/
