[build]
  publish = "_site"
  command = "bash ./scripts/netlify-build.sh"

[build.environment]
  #PHP_VERSION = "7.4"

[context.production.environment]
  CECIL_ENV = "production"

[context.deploy-preview.environment]
  CECIL_ENV = "preview"
